
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=120d' # Adjust retention as needed
      - '--web.enable-remote-write-receiver' # IMPORTANT - Enable remote write receiver
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - prom_data:/prometheus
      - ./prometheus:/etc/prometheus
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=SOMEPASSWORD # IMPORTANT - CHANGE THIS
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - ./grafana_data:/var/lib/grafana
volumes:
  prom_data:
  grafana_data:

